
version: '3'
services:
  app:
    container_name: django-mpesapy
    build:
      dockerfile: Dockerfile
      context: .
    image: wanderijames/django-mpesapy
    command: bash -c "cd /usr/local/lib/django-mpesapy && pip install -e . && cd example_project && sleep 3600"
    ports:
      - "8001:8001"
    volumes:
      - .:/usr/local/lib/django-mpesapy