# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-09 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.BooleanField(default=False)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('urlsafe', models.CharField(blank=True, editable=False, max_length=256, null=True)),
                ('ref', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('extra', models.TextField(blank=True, help_text=b'important data', null=True)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.FloatField(blank=True, max_length=100, null=True)),
                ('bnt', models.CharField(choices=[((b'B2C',), (b'B2C',)), (b'B2B', b'B2B'), (b'C2BB', b'C2B Paybill'), (b'C2BT', b'C2B Till'), (b'C2BC', b'C2B Checkout')], db_index=True, default=b'C2BB', help_text=b'Business number type', max_length=5)),
                ('extra', models.TextField(blank=True, help_text=b'important data', null=True)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('amount', models.FloatField(blank=True, max_length=100, null=True)),
                ('msisdn', models.CharField(blank=True, max_length=150, null=True)),
                ('person', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[(b'CONS', b'Consumed'), (b'HELD', b'Held'), (b'DECL', b'Declined'), (b'REJE', b'Rejected')], db_index=True, default=b'HELD', max_length=5)),
                ('extra', models.TextField(blank=True, help_text=b'important data', null=True)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesabase_business', to='mpesapy.Business')),
            ],
        ),
        migrations.CreateModel(
            name='MpesaCtoBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.BooleanField(default=False)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('urlsafe', models.CharField(blank=True, editable=False, max_length=256, null=True)),
                ('ipn_notification_id', models.CharField(blank=True, help_text=b'Notification ID', max_length=20, null=True)),
                ('text_message', models.CharField(blank=True, max_length=200, null=True)),
                ('mpesa_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('mpesa_amt', models.FloatField(blank=True, max_length=100, null=True)),
                ('mpesa_msisdn', models.CharField(blank=True, max_length=150, null=True)),
                ('mpesa_sender', models.CharField(blank=True, max_length=200, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('date_processed', models.DateTimeField(auto_now=True)),
                ('counter_checked', models.BooleanField(default=False)),
                ('notification_source', models.CharField(blank=True, help_text=b'Notification source', max_length=100, null=True)),
                ('notification_destination', models.CharField(blank=True, help_text=b'Notification destination', max_length=100, null=True)),
                ('mpesa_acc', models.CharField(db_index=True, max_length=200)),
                ('mpesa_trx_date', models.CharField(max_length=100)),
                ('mpesa_trx_time', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'M-Pesa C2B',
                'verbose_name_plural': 'M-Pesa C2Bs',
            },
        ),
        migrations.CreateModel(
            name='MpesaCtoBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.BooleanField(default=False)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('urlsafe', models.CharField(blank=True, editable=False, max_length=256, null=True)),
                ('ipn_notification_id', models.CharField(blank=True, help_text=b'Notification ID', max_length=20, null=True)),
                ('text_message', models.CharField(blank=True, max_length=200, null=True)),
                ('mpesa_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('mpesa_amt', models.FloatField(blank=True, max_length=100, null=True)),
                ('mpesa_msisdn', models.CharField(blank=True, max_length=150, null=True)),
                ('mpesa_sender', models.CharField(blank=True, max_length=200, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('date_processed', models.DateTimeField(auto_now=True)),
                ('counter_checked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'M-Pesa C2Buy',
                'verbose_name_plural': 'M-Pesa C2Buys',
            },
        ),
    ]
