# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-09 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesapy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
