# Generated by Django 3.0 on 2020-01-06 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpesapy', '0005_requestlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='extra',
            field=models.TextField(blank=True, help_text='important data', null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='bnt',
            field=models.CharField(choices=[('B2C', 'B2C'), ('B2B', 'B2B'), ('C2BB', 'C2B Paybill'), ('C2BT', 'C2B Till'), ('C2BC', 'C2B Checkout')], db_index=True, default='C2BB', help_text='Business number type', max_length=5),
        ),
        migrations.AlterField(
            model_name='business',
            name='extra',
            field=models.TextField(blank=True, help_text='important data', null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='register',
            field=models.BooleanField(default=False, help_text='Register URL'),
        ),
        migrations.AlterField(
            model_name='business',
            name='registered',
            field=models.BooleanField(default=False, help_text='Is URL registered'),
        ),
        migrations.AlterField(
            model_name='mpesabase',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mpesabase_business', to='mpesapy.Business'),
        ),
        migrations.AlterField(
            model_name='mpesabase',
            name='extra',
            field=models.TextField(blank=True, help_text='important data', null=True),
        ),
        migrations.AlterField(
            model_name='mpesabase',
            name='status',
            field=models.CharField(choices=[('CONS', 'Consumed'), ('HELD', 'Declined'), ('DECL', 'Held'), ('REJE', 'Rejected')], db_index=True, default='DECL', max_length=5),
        ),
        migrations.AlterField(
            model_name='mpesactobill',
            name='ipn_notification_id',
            field=models.CharField(blank=True, help_text='Notification ID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mpesactobill',
            name='notification_destination',
            field=models.CharField(blank=True, help_text='Notification destination', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mpesactobill',
            name='notification_source',
            field=models.CharField(blank=True, help_text='Notification source', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mpesactobuy',
            name='ipn_notification_id',
            field=models.CharField(blank=True, help_text='Notification ID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='requestlogs',
            name='body',
            field=models.TextField(help_text='Request body'),
        ),
        migrations.AlterField(
            model_name='requestlogs',
            name='path',
            field=models.CharField(help_text='Request path', max_length=100),
        ),
    ]
